### ISSUE TITLE
ESP32 not connecting to strongest WiFi network when having multiple APs with the same SSID

### ISSUE THREAD

**Issue by rastanico** [InnuendoPi/Brautomat32#1]
Hi Innu, first of all many thanks for providing this project, it made me already some wonderful tasty beers!

I brew in the basement where wifi signal is bad, so I installed a repeater between my router and the Brautomat, which repeats the SSID from the Router. Brautomat still mostly connects to the Router WiFi instead of the stronger one from the repeater. 
The repeated wifi uses the same ssid and crypto. I made the wifi setup procedure again many times without sucess.
If you are willing to share the source code of the wifi part, I can read the docs by myself and try to find a solution and propose it.

Thank you, best regards,

Nico

**Comment by rastanico** [comment]
I don't have a solution now, but this seems to be a known issue of esp32/wifimanager lib:

https://forum.arduino.cc/t/esp32-fritz-box-mesh-same-ssid-for-router-repeater-force-connecting-to-a-certain-mac-adress/1160028/6

https://github.com/tzapu/WiFiManager/issues/221

**Comment by InnuendoPi** [comment]
Hey Nico,
Brautomat uses libs like WiFi, WiFiManager etc as is. My firmware can not handle WLAN problems. By the way: I've setup a WLAN mesh at home months ago (Fritz!box 7590AX, 3 repeaters 1200AX, version 7.57). My brewery is in the basement. Brautomat (ESP8266 and ESP32) always connect to the nearest repeater (in the same room).
Innu

**Comment by InnuendoPi** [comment]
Closed as this problems seems not to be a firmware issue

**Comment by InnuendoPi** [comment]
Closed, not a firmware issue
