### ISSUE TITLE
Am Nextion Display funktioniert der manuelle Mode und MaischeSud Ansicht nicht

### ISSUE THREAD

**Issue by Schmuckerl** [InnuendoPi/Brautomat32#2]
- Beim manuellen Mode ist die Temperatur immer auf 0
- IDS 2 Einstellung kann man zwar machen, aber wird nicht auf IDS übertragen.
- MaischeSud Ansicht zeigt keine Werte
- Kessel Ansicht funktioniert

Hab die K Version vom Display

Bin auf der aktuellen Version, was kann es da haben?

Danke!!

**Comment by InnuendoPi** [comment]
Der manuelle Modus ist auf dem Display z. Z. nur eine Anzeige. Bitte den Web Browser verwenden. Ich habe soeben einen ESP32 und ein Display T035 neu bespielt: die Temperatur wird im manuellen Modus korrekt angezeigt. Die Ansicht MaischeSud funktioniert normal. Ich kann keine Fehler feststellen. Bitte prüfen, ob die korrekte Firmware auf dem Display aufgespielt ist.  Brautomat und MQTTDevice sind unterschiedlich.

**Comment by Schmuckerl** [comment]
Servus,
danke mal für die schnelle Antwort.
Habe die Display Firmware geprüft, war die richtige drauf, hab dann noch mal die Firmware raufgespielt, ohne Verbesserung.
Keine Temp beim manuellen Mode und keine Anzeige bei Ansicht MaischeSud.
Kann es sein, dass die K035 ein Problem hat?
Danke!

**Comment by InnuendoPi** [comment]
Ist mir nicht bekannt und halte ich für sehr unwahrscheinlich. Bitte sende mir im Forum Deine config.txt

**Comment by Schmuckerl** [comment]
[config.txt](https://github.com/user-attachments/files/17253637/config.txt)

Danke!

**Comment by InnuendoPi** [comment]
In Deiner config ist kein Fehler und mein Display zeigt mit Deiner config alles korrekt an. Du verwendest einen ESP8266. Das Thema gehört dann "eigentlich" ins repository brautomat (brautomat32 -> ESP32).
In der ESP8266 Version habe ich einen Fehler (OOM Exception) gefunden. Möglicherweise eine Fehlerursache bei Deinem Brautomat. Aktiviere bitte unter System -> Backup & Restore -> WebUpdate mit Testversion. Dann starte ein WebUpdate auf Version 1.46.4.

**Comment by Schmuckerl** [comment]
Servus, woran kennst du, dass ich den ESP8266 verwende? Ich hab den az delivery esp32 wroom 32 (ESP32-D0WD-V3) im Einsatz (ist eh von dir). Hab gerade den Upgrade auf Dev gemacht, zeigt immer noch 1.46.1 (mit dev) an (vermutlich weil ESP32), geändert hat sich nichts. Was ich aber gerade bemerkt habe, ist dass nur die Ansicht im Display funktioniert, die ich als Startseite in den Einstellungen gewählt habe! Jetzt geht z.B. die Temp Anzeige im manuellen Modus, alles andere nicht! Wenn ich auf MaischeSud gehe, funktioniert nur MaischeSud usw.

**Comment by InnuendoPi** [comment]
Ich habe leider keine k035 Display für Tests. Alle Display Dateien habe ich nochmal neu erstellt und auf github hinterlegt. Für den ESP32 habe ich die Testversion 1.46.4 bereitgestellt. Es gab bislang keinen User mit Display Problemen. Welche Displaytypen (F035, K035 oder T035) im Einsatz sind, weiß ich nicht. Aktualisiere bitte die Firmware Display und den Brautomat32 mit Testversion. Bitte schreibe im Hobbybrauerforum per PN weiter.

**Comment by Schmuckerl** [comment]
Grüß dich!
Ich glaube du musst noch die 1.46.6 Version hochladen, auf beiden Branches sind noch die .5, im Changelog sprichst du von .6
Mit der .5 und neuer Display Firmware funzt es leider noch nicht!
Dankeschön!

**Comment by Schmuckerl** [comment]
Danke, aber es will meine K035 einfach nicht. Leider keine Veränderung!

**Comment by InnuendoPi** [comment]
Flashe Deinen Brautomaten vollständig neu (flashen.cmd im ZIP File). Wenn vorhanden aktiviere Deinen Piezo Buzzer. Bei einem Seitenwechsel ertönt ein kurzer Signalton.

**Comment by Schmuckerl** [comment]
leider ohne Erfolg. Alles neu geflasht und konfiguriert, alles beim Alten. Und beim Seitenwechsel gibt es auch keinen Ton.

**Comment by Schmuckerl** [comment]
Hallo nochmal! Habe die Pins verfolgt und eine kalte Lötstelle beim SDL Pin gefunden! Jetzt funktioniert alles wie gewünscht. Sorry für deinen Aufwand! Danke nochmal! Super Projekt und Support!
